import User from './models/user.js';
import bcrypt from 'bcrypt';

const karyawanData = [
    { nama_lengkap: "Arik Candra Santoso", role: "chief", pos: "Screening", nip: "20241339", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Maulana Haryo H", role: "assistant_chief", pos: "Screening", nip: "20245230", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Diah Yulistia", role: "assistant_chief", pos: "Screening", nip: "20244465", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arda Pradana", role: "assistant_chief", pos: "Screening", nip: "20245109", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Nia Agustina", role: "assistant_chief", pos: "Screening", nip: "20246709", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Bagus Purhito", role: "officer", pos: "Screening", nip: "2407029", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Purna Anang Prayogi", role: "officer", pos: "Screening", nip: "2407101", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Richy Effendi", role: "officer", pos: "Screening", nip: "2300850", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Bayu Kurniawan", role: "officer", pos: "Screening", nip: "2407030", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Suwardi", role: "officer", pos: "Screening", nip: "2407130", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Aditya Warman", role: "officer", pos: "Screening", nip: "2407009", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Yan Sonaval Saputra", role: "officer", pos: "Screening", nip: "2407147", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dwi Iryanto", role: "officer", pos: "Screening", nip: "2407041", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ni Luh Dessy Kusumawati", role: "officer", pos: "Screening", nip: "2407086", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Herdinawan Siringo Ringo", role: "officer", pos: "Screening", nip: "2407056", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Yosanda Viyo Badiyaningrum", role: "officer", pos: "Screening", nip: "2407148", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Rahardhian Wibawa Putra", role: "officer", pos: "Screening", nip: "2407106", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Sinto Haryo Yudanto", role: "officer", pos: "Screening", nip: "2407119", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Zainal Abidin", role: "officer", pos: "Screening", nip: "1901070", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Rachmat Senati Wicaksono", role: "officer", pos: "Screening", nip: "2407105", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Miftakul Anam", role: "officer", pos: "Screening", nip: "1901069", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Fajar Alfian Mawardi", role: "officer", pos: "Screening", nip: "2303493", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ahmad Qoharur Rijal", role: "officer", pos: "Screening", nip: "2501864", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Theresia Latri Utami", role: "officer", pos: "Screening", nip: "2202323", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Aprilia Alfionita", role: "officer", pos: "Screening", nip: "2403656", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Afifah Khoiriyani", role: "officer", pos: "Screening", nip: "2002417", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arif Hermawan", role: "officer", pos: "Screening", nip: "2403659", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Nur Iksan Yulia", role: "officer", pos: "Screening", nip: "2502521", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Reza Firmansyah", role: "officer", pos: "Screening", nip: "2403675", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Edy Santoso", role: "officer", pos: "Screening", nip: "2403662", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arya Adi Prasetiya", role: "officer", pos: "Screening", nip: "2202210", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dhimas Prasetyo Suryondaru", role: "officer", pos: "Screening", nip: "2001952", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Irvan Yuliantoro", role: "officer", pos: "Screening", nip: "2304057", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arif Rahman", role: "chief", pos: "Screening", nip: "20240763", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Anna Wulandari", role: "assistant_chief", pos: "Screening", nip: "20244042", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Haryono", role: "assistant_chief", pos: "Screening", nip: "20244011", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Lintang Giri Budinata", role: "assistant_chief", pos: "Screening", nip: "20246451", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Sutarjo", role: "officer", pos: "Screening", nip: "2407129", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Eko Saputro", role: "officer", pos: "Screening", nip: "2407045", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Rixy Bagaskara", role: "officer", pos: "Screening", nip: "2407114", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Joko Suprastyo", role: "officer", pos: "Screening", nip: "2407070", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ega Bayu Adi Pratama", role: "officer", pos: "Screening", nip: "2407042", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Kukuh Galant Apriano", role: "officer", pos: "Screening", nip: "2202262", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Sumantri", role: "officer", pos: "Screening", nip: "2407125", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Iskak Muhroji", role: "officer", pos: "Screening", nip: "2407062", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ardhian Wibowo", role: "officer", pos: "Screening", nip: "2407023", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Mardian Jimi Utomo", role: "officer", pos: "Screening", nip: "2407077", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Heni Heryanti", role: "officer", pos: "Screening", nip: "2407055", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Tanjung Martasari", role: "officer", pos: "Screening", nip: "2407131", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Yuli Astutik", role: "officer", pos: "Screening", nip: "2407150", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Vina Adinda Rohmadiyani", role: "officer", pos: "Screening", nip: "2300984", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Miftakhul Amin", role: "officer", pos: "Screening", nip: "2500895", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Anggara Dika Montana", role: "officer", pos: "Screening", nip: "1902964", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Kukuh Rian Kurniawan", role: "officer", pos: "Screening", nip: "2301876", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Juli Dwi Wijaya", role: "officer", pos: "Screening", nip: "2402807", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dika Anindita Ramadhani", role: "officer", pos: "Screening", nip: "2001946", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Evi Mayasari", role: "officer", pos: "Screening", nip: "2002439", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ayu Tri Widyastuti", role: "officer", pos: "Screening", nip: "2411023", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Fakassin Kuluqi", role: "officer", pos: "Screening", nip: "2403276", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Adnan Aries Wimatama", role: "officer", pos: "Screening", nip: "2202198", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Oktoberiandy", role: "officer", pos: "Screening", nip: "2202281", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arif Budi Zakaria", role: "officer", pos: "Screening", nip: "2301456", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Faizal Rofiq Romadhoni", role: "officer", pos: "Screening", nip: "2403664", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muhammad Zidan Aqila Ratmera", role: "officer", pos: "Screening", nip: "2502523", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arhan Fauzianto", role: "officer", pos: "Screening", nip: "2002425", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Qodariah Timorianti", role: "chief", pos: "Screening", nip: "20241317", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ismu Prasetya", role: "assistant_chief", pos: "Screening", nip: "20244003", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Yudhanto Andhi Handoko", role: "assistant_chief", pos: "Screening", nip: "20244480", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Kamelia", role: "assistant_chief", pos: "Screening", nip: "20246589", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Sodik Joko Purnomo", role: "officer", pos: "Screening", nip: "2407120", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Sunarto", role: "officer", pos: "Screening", nip: "2407127", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Satria Ari Wibawa", role: "officer", pos: "Screening", nip: "2407117", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Aslama Addinul Hasan", role: "officer", pos: "Screening", nip: "2407028", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Haryadi", role: "officer", pos: "Screening", nip: "2407054", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Aldi Budiman", role: "officer", pos: "Screening", nip: "2407015", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Kiki Yahya Saputra", role: "officer", pos: "Screening", nip: "2407071", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dhanur Febianto", role: "officer", pos: "Screening", nip: "2407037", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Pradipta Indra Putra Wibowo", role: "officer", pos: "Screening", nip: "2407096", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Rifky Faisal Riandy", role: "officer", pos: "Screening", nip: "2407110", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ana Dwi Astuti", role: "officer", pos: "Screening", nip: "2407017", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Winarni", role: "officer", pos: "Screening", nip: "2407146", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Annisa Fauziyah", role: "officer", pos: "Screening", nip: "2407022", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Lugas Manggala Widigda Erlangga", role: "officer", pos: "Screening", nip: "1902966", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Novianto", role: "officer", pos: "Screening", nip: "1901423", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Fuad Dewa Ramdhani", role: "officer", pos: "Screening", nip: "1901058", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Wahyu Kusbiyanto", role: "officer", pos: "Screening", nip: "2202327", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muchamad Isa Alamsyah Syahlan", role: "officer", pos: "Screening", nip: "2407080", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dina Mawalia Puspitaningrum", role: "officer", pos: "Screening", nip: "2403661", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Nindia Mukti Wulansari", role: "officer", pos: "Screening", nip: "2002456", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Deddy Kurniawan", role: "officer", pos: "Screening", nip: "2403660", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Rizki Subekti", role: "officer", pos: "Screening", nip: "2208688", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Bekti Dwi Wicaksono", role: "officer", pos: "Screening", nip: "2002449", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Tri Yoga Baskoro", role: "officer", pos: "Screening", nip: "2208689", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dwi Prasetya", role: "officer", pos: "Screening", nip: "2304365", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ryan Rizki Setyawan", role: "officer", pos: "Screening", nip: "2300978", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Mega Krisna Hidayat", role: "officer", pos: "Screening", nip: "2402810", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Fitri Ana Astuti", role: "officer", pos: "Screening", nip: "2001968", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Wahyu Agus L.", role: "chief", pos: "Screening", nip: "20241892", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ardyn Nurrahmawan", role: "assistant_chief", pos: "Screening", nip: "20244014", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Adin Vita Jati", role: "assistant_chief", pos: "Screening", nip: "20244456", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ponco Achmad Nur Rohim", role: "assistant_chief", pos: "Screening", nip: "20246383", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dwi Latri Sutoro", role: "officer", pos: "Screening", nip: "2202232", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Heroes Septima", role: "officer", pos: "Screening", nip: "2407058", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Morgan Lucky Atmaja", role: "officer", pos: "Screening", nip: "2407079", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Joko Siswadi", role: "officer", pos: "Screening", nip: "2407069", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "I Nyoman Yudana Dharma Githa", role: "officer", pos: "Screening", nip: "2202251", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Bayu Irawan Saputra", role: "officer", pos: "Screening", nip: "2202215", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Rudi Setiawan", role: "officer", pos: "Screening", nip: "2202304", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Purnama", role: "officer", pos: "Screening", nip: "2202290", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Wahyu Fajar Cahyana", role: "officer", pos: "Screening", nip: "2407140", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Istiningsih", role: "officer", pos: "Screening", nip: "2407064", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Islakhul Asror", role: "officer", pos: "Screening", nip: "2407063", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Norma Dwi Titisavi Cahyaningtyas", role: "officer", pos: "Screening", nip: "2407089", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Heri Supriyanto", role: "officer", pos: "Screening", nip: "2407057", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Disdian Sandiaka", role: "officer", pos: "Screening", nip: "2202228", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Mahmud Ireng Ismanto", role: "officer", pos: "Screening", nip: "2407076", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muhammad Iqbal", role: "officer", pos: "Screening", nip: "2301451", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Raden Ilham Muhammad Farijd", role: "officer", pos: "Screening", nip: "2500899", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Augusta Yudo Indrianto", role: "officer", pos: "Screening", nip: "2001974", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Wenda Zelyca Rachma", role: "officer", pos: "Screening", nip: "2202328", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muizatul Hasanah", role: "officer", pos: "Screening", nip: "2002454", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Siti Apsoh", role: "officer", pos: "Screening", nip: "2403676", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Diki Adi Sanjaya", role: "officer", pos: "Screening", nip: "2300979", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Didik Triantoro Isbiantoko", role: "officer", pos: "Screening", nip: "2202226", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Wisnu Saputro", role: "officer", pos: "Screening", nip: "2002523", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muhammad Dikie Mahendra Putra", role: "officer", pos: "Screening", nip: "2001960", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Erastus Eldy Lenardo Cahyo K.", role: "officer", pos: "Screening", nip: "2202238", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Nasrodin", role: "officer", pos: "Screening", nip: "2300980", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Yuda Wira Kusuma", role: "officer", pos: "Screening", nip: "2402806", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dina Nurmaladewi", role: "chief", pos: "Terminal Protection", nip: "20241351", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Hawky Aryatama Sanjaya", role: "assistant_chief", pos: "Terminal Protection", nip: "20246682", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Pambudi Sasangka Aji", role: "officer", pos: "Terminal Protection", nip: "2407093", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Yosua Krissantono", role: "officer", pos: "Terminal Protection", nip: "1901050", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Putra Dwi Santoso", role: "officer", pos: "Terminal Protection", nip: "2407102", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Fadli Nurohman Wakhid", role: "officer", pos: "Terminal Protection", nip: "2407049", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Birzha Khafitdalloh", role: "officer", pos: "Terminal Protection", nip: "2407032", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dodyd Irsyad Rafif", role: "officer", pos: "Terminal Protection", nip: "2500889", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arista Puteri Windarningsih", role: "officer", pos: "Terminal Protection", nip: "2407026", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Mirnawati", role: "officer", pos: "Terminal Protection", nip: "2501843", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arif Catur Swantoro", role: "officer", pos: "Terminal Protection", nip: "1901657", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arif Dwi Irfanto", role: "officer", pos: "Terminal Protection", nip: "1901066", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Indra Arfa Rimawan", role: "officer", pos: "Terminal Protection", nip: "2500894", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ferry Aryandi Ervianto", role: "officer", pos: "Terminal Protection", nip: "2501839", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Sahrul Gunawan", role: "officer", pos: "Terminal Protection", nip: "1901992", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Mimbar Arum Purbawinata", role: "officer", pos: "Terminal Protection", nip: "1901112", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Roy Rhomadona", role: "chief", pos: "Terminal Protection", nip: "20241869", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Anggir Riyanto", role: "assistant_chief", pos: "Terminal Protection", nip: "20243980", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Bayu Rahmanto", role: "officer", pos: "Terminal Protection", nip: "2407031", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Oni Suryono", role: "officer", pos: "Terminal Protection", nip: "2407092", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Prasetyo Wijonarko", role: "officer", pos: "Terminal Protection", nip: "2407097", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Avent Anfaza Noor", role: "officer", pos: "Terminal Protection", nip: "1804269", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "James Philar Dananjaya", role: "officer", pos: "Terminal Protection", nip: "2501841", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muhammad Syafiil Huda", role: "officer", pos: "Terminal Protection", nip: "2407084", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Bagus Prabowo", role: "officer", pos: "Terminal Protection", nip: "2402016", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Hari Purwantoro", role: "officer", pos: "Terminal Protection", nip: "2501840", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Wuryani", role: "officer", pos: "Terminal Protection", nip: "2500904", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Heriyanto", role: "officer", pos: "Terminal Protection", nip: "1901041", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arifian Jihad Putranto", role: "officer", pos: "Terminal Protection", nip: "2210217", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muhamat Lanang Maulana", role: "officer", pos: "Terminal Protection", nip: "2210218", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Septian Adiputra", role: "officer", pos: "Terminal Protection", nip: "2407118", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arditiya Yoga Pratama", role: "officer", pos: "Terminal Protection", nip: "2500882", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Didik Slamet Santoso", role: "chief", pos: "Terminal Protection", nip: "20242382", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "I Wayan Gede Dwi Adnyana P", role: "assistant_chief", pos: "Terminal Protection", nip: "20247302", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Benny Rilo Pambudi", role: "assistant_chief", pos: "Terminal Protection", nip: "20246605", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Putut Hatmojo", role: "officer", pos: "Terminal Protection", nip: "2407104", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dodi Ariesta Kusuma Wardana", role: "officer", pos: "Terminal Protection", nip: "2202229", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Zainurrokhim", role: "officer", pos: "Terminal Protection", nip: "2407152", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Chandra Diky Indrayanto", role: "officer", pos: "Terminal Protection", nip: "2407034", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Sidiq Rachman", role: "officer", pos: "Terminal Protection", nip: "2501849", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Gayuh Dwisakti Kurnianto", role: "officer", pos: "Terminal Protection", nip: "2304364", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Riyadi Pramono", role: "officer", pos: "Terminal Protection", nip: "2500900", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muhammad Fatkurohman", role: "officer", pos: "Terminal Protection", nip: "2407083", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Sumistar", role: "officer", pos: "Terminal Protection", nip: "2202314", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Guntur Adhi Nuhroho", role: "officer", pos: "Terminal Protection", nip: "2210403", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Vina Apriyani", role: "officer", pos: "Terminal Protection", nip: "2500902", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Adhitiya Pamungkas", role: "officer", pos: "Terminal Protection", nip: "2411024", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Daffa Maulana Rivanny", role: "officer", pos: "Terminal Protection", nip: "2502522", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Suko Raharjo", role: "chief", pos: "Terminal Protection", nip: "20240440", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dhistira Agung Pramana", role: "assistant_chief", pos: "Terminal Protection", nip: "20246066", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Eko Prasetiyo", role: "officer", pos: "Terminal Protection", nip: "2202235", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arif Khalil Al Patah", role: "officer", pos: "Terminal Protection", nip: "2202208", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dicky Satriya Setiyawan", role: "officer", pos: "Terminal Protection", nip: "2500887", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "David Putrananta", role: "officer", pos: "Terminal Protection", nip: "2500884", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Zulfikar Awaluddin", role: "officer", pos: "Terminal Protection", nip: "2105562", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Nuria Wulan Sari", role: "officer", pos: "Terminal Protection", nip: "2500897", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Riky Doner Edgar Damara", role: "officer", pos: "Terminal Protection", nip: "2407111", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Febriarto Malik Alkarim", role: "officer", pos: "Terminal Protection", nip: "2407051", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Sarif Purnama", role: "officer", pos: "Terminal Protection", nip: "2501848", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Wahyu Parasamya", role: "officer", pos: "Terminal Protection", nip: "2500903", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muhammad Prasetyo Bayu Adji", role: "officer", pos: "Terminal Protection", nip: "1901107", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Devi Setia Sari", role: "officer", pos: "Terminal Protection", nip: "2302564", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muhammad Irfan", role: "officer", pos: "Terminal Protection", nip: "2302565", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Riang Putra Utama", role: "officer", pos: "Terminal Protection", nip: "2202296", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Defri Armanda Sulanggri", role: "chief", pos: "Non-Terminal Protection", nip: "20241893", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Heri Kuncoro", role: "assistant_chief", pos: "Non-Terminal Protection", nip: "20246330", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Wiji Purnomo", role: "officer", pos: "Non-Terminal Protection", nip: "2407145", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ramadhan Ebri Bagus Pratama", role: "officer", pos: "Non-Terminal Protection", nip: "2300851", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ervin", role: "officer", pos: "Non-Terminal Protection", nip: "2501837", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Agus Sunarto", role: "officer", pos: "Non-Terminal Protection", nip: "2500881", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Aditya Darmawan", role: "officer", pos: "Non-Terminal Protection", nip: "2501830", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Herbangun Suwisma", role: "officer", pos: "Non-Terminal Protection", nip: "1901083", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Maulana Agwar Dwiputra", role: "officer", pos: "Non-Terminal Protection", nip: "2300977", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Eko Budi Nugroho", role: "officer", pos: "Non-Terminal Protection", nip: "2407043", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dwi Andika Rochman", role: "chief", pos: "Non-Terminal Protection", nip: "20241901", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Syahrozi", role: "assistant_chief", pos: "Non-Terminal Protection", nip: "20246707", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Agus Adi Saputra", role: "officer", pos: "Non-Terminal Protection", nip: "2407012", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Hestian Agung Prayoga", role: "officer", pos: "Non-Terminal Protection", nip: "2500893", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Joko Dwi Atmaji", role: "officer", pos: "Non-Terminal Protection", nip: "2407066", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Tri Edi Santoso", role: "officer", pos: "Non-Terminal Protection", nip: "1901047", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muh. Imran", role: "officer", pos: "Non-Terminal Protection", nip: "2407081", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Eko Priyo Prabowo", role: "officer", pos: "Non-Terminal Protection", nip: "1901034", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ngatijo", role: "officer", pos: "Non-Terminal Protection", nip: "2501845", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Danang Setyawan Prakoso", role: "officer", pos: "Non-Terminal Protection", nip: "2300849", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Puji Suyono", role: "chief", pos: "Non-Terminal Protection", nip: "20240049", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Adittia Prasetyo", role: "assistant_chief", pos: "Non-Terminal Protection", nip: "20244469", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Achmad Ryo Wahyudi", role: "officer", pos: "Non-Terminal Protection", nip: "2407007", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Unggul Fadhil Muhammad", role: "officer", pos: "Non-Terminal Protection", nip: "2208690", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ritko Edi Triamanto", role: "officer", pos: "Non-Terminal Protection", nip: "2407113", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Galih Riadi", role: "officer", pos: "Non-Terminal Protection", nip: "1901036", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Nur Wahyudi", role: "officer", pos: "Non-Terminal Protection", nip: "2208687", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Anggit Prabawa Guratama", role: "officer", pos: "Non-Terminal Protection", nip: "1901033", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ali Usman", role: "officer", pos: "Non-Terminal Protection", nip: "2501833", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Patrick Tegar Rengga R.", role: "officer", pos: "Non-Terminal Protection", nip: "2500898", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Hawing Yuliantoro", role: "chief", pos: "Non-Terminal Protection", nip: "20241989", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Dedi Felani", role: "assistant_chief", pos: "Non-Terminal Protection", nip: "20243986", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Bayu Ridho Fawzi", role: "officer", pos: "Non-Terminal Protection", nip: "2202217", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Murdiantoro", role: "officer", pos: "Non-Terminal Protection", nip: "1901056", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Taufik Yunus", role: "officer", pos: "Non-Terminal Protection", nip: "2202320", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Deny Fardana Saputra", role: "officer", pos: "Non-Terminal Protection", nip: "2500885", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Kossa Dean Herry Pratama", role: "officer", pos: "Non-Terminal Protection", nip: "2407072", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Arga Sugiarto", role: "officer", pos: "Non-Terminal Protection", nip: "2301452", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Firmansyah", role: "officer", pos: "Non-Terminal Protection", nip: "2301455", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Rafdi Fitra Riza", role: "officer", pos: "Non-Terminal Protection", nip: "2503700", bandara: "Yogyakarta International Airport" },
    
    { nama_lengkap: "YIA. OP", role: "superadmin", pos: "", nip: "", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "YIA. OC", role: "superadmin", pos: "", nip: "", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Rahmad Riyadi HB", role: "admin", pos: "", nip: "", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Ida Ayu Wika Widyastusi", role: "admin", pos: "", nip: "", bandara: "Yogyakarta International Airport" },
    { nama_lengkap: "Muhammad Yudha Abdillah", role: "admin", pos: "", nip: "", bandara: "Yogyakarta International Airport" },
    
];

async function seedKaryawan() {
    try {
        console.log('Memulai seeding karyawan...');
        
        // Hash password untuk semua user
        const hashedPassword = await bcrypt.hash('password123', 10);
        
        // Siapkan data dengan password yang sudah di-hash dan field tambahan
        const usersToCreate = karyawanData.map(user => ({
            nip: user.nip,
            nama_lengkap: user.nama_lengkap,
            email: `${user.nip}@yia.co.id`, // Generate email dari NIP
            password: hashedPassword,
            lokasi: "", // Kosong sesuai format asli
            pos: user.pos,
            shift: null, // Null sesuai format asli
            role: user.role,
            bandara: user.bandara,
            first_login: true
        }));
        
        // Insert data dengan ignoreDuplicates untuk menghindari error jika ada data duplikat
        await User.bulkCreate(usersToCreate, { 
            ignoreDuplicates: true,
            validate: true
        });
        
        console.log(`${karyawanData.length} karyawan berhasil ditambahkan ke database!`);
        console.log('Password default untuk semua user: password123');
        console.log('Email format: [NIP]@yia.co.id');
        
    } catch (error) {
        console.error('Error saat seeding karyawan:', error);
        if (error.errors) {
            error.errors.forEach(err => {
                console.error(`- ${err.message}`);
            });
        }
    }
}

// Jalankan seeder
seedKaryawan();

