import WalkingPatrolNonTerminalUraian from "./walking_patrol_non_terminal_uraian.js";
import WalkingPatrolNonTerminalMaster from "./walking_patrol_non_terminal_master.js";
import WalkingPatrolMaster from "./walking_patrol_master.js";
import WalkingPatrolChecklist from "./walking_patrol_checklist.js";
import UraianTugas from "./uraian_tugas.js";
import LogbookHarianMaster from "./logbook_harian_master.js";
import UraianInventaris from "./uraian_inventaris.js";
import SuspiciousUraian from "./suspicious_uraian.js";
import SuspiciousMaster from "./suspicious_master.js";
import RotasiPersonelUraian from "./rotasi_personel_uraian.js";
import RotasiPersonelMaster from "./rotasi_personel_master.js";
import PatrolUdaraUraian from "./patrol_udara_uraian.js";
import PatroliUdaraMaster from "./patroli_udara_master.js";
import PatrolDaratUraian from "./patrol_darat_uraian.js";
import PatroliDaratMaster from "./patroli_darat_master.js";
import LogbookRaUraian from "./logbook_ra_uraian.js";
import LogbookRaMaster from "./logbook_ra_master.js";
import LaporanTerminalKargoUraian from "./laporan_terminal_kargo_uraian.js";
import LaporanTerminalKargoMaster from "./laporan_terminal_kargo_master.js";
import LaporanPatroliRandomUraian from "./laporan_patroli_random_uraian.js";
import LaporanPatroliRandomMaster from "./laporan_patroli_random_master.js";
//import FormKemajuanPersonelUraian from "./form_kemajuan_personel_uraian.js";
import FormKemajuanPersonelMaster from "./form_kemajuan_personel_master.js";
import ChecklistPenyisiran from "./checklist_penyisiran.js";
import PenyisiranRuangTungguMaster from "./penyisiran_ruang_tunggu_master.js";
import BehaviourUraian from "./behaviour_uraian.js";

import BehaviourMaster from "./behaviour_master.js";
import ChecklistHarianPatroliUraian from "./checklist_harian_patroli_uraian.js";
import ChecklistHarianPatroliMaster from "./checklist_harian_patroli_master.js";

import UraianPI from "./uraian_pi.js";
import FormPengendalianPI from "./form_pengendalian_pi.js";
import UraianGate from "./uraian_gate.js";


// Relasi antar model
BehaviourUraian.belongsTo(BehaviourMaster, { foreignKey: "behaviour_master_id", as: "behaviour_master_detail" });
BehaviourMaster.hasMany(BehaviourUraian, { foreignKey: "behaviour_master_id", as: "behaviour_uraian_list" });
WalkingPatrolNonTerminalUraian.belongsTo(WalkingPatrolNonTerminalMaster, { foreignKey: "walking_patrol_non_terminal_master_id", as: "walking_patrol_non_terminal_master" });
WalkingPatrolNonTerminalMaster.hasMany(WalkingPatrolNonTerminalUraian, { foreignKey: "walking_patrol_non_terminal_master_id", as: "walking_patrol_non_terminal_uraian_list" });
WalkingPatrolMaster.hasMany(WalkingPatrolChecklist, { foreignKey: "walking_patrol_master_id", as: "walking_patrol_checklist_list" });
WalkingPatrolChecklist.belongsTo(WalkingPatrolMaster, { foreignKey: "walking_patrol_master_id", as: "walking_patrol_master_detail" });
UraianTugas.belongsTo(LogbookHarianMaster, { foreignKey: "logbook_harian_master_id", as: "logbook_harian_master_detail" });
LogbookHarianMaster.hasMany(UraianTugas, { foreignKey: "logbook_harian_master_id", as: "uraian_tugas_list" });
UraianInventaris.belongsTo(LogbookHarianMaster, { foreignKey: "logbook_harian_master_id", as: "logbook_harian_master_inventaris" });
LogbookHarianMaster.hasMany(UraianInventaris, { foreignKey: "logbook_harian_master_id", as: "uraian_inventaris_list" });
SuspiciousUraian.belongsTo(SuspiciousMaster, { foreignKey: "suspicious_master_id", as: "suspicious_master" });
SuspiciousMaster.hasMany(SuspiciousUraian, { foreignKey: "suspicious_master_id", as: "suspicious_uraian_list" });
RotasiPersonelUraian.belongsTo(RotasiPersonelMaster, { foreignKey: "rotasi_personel_master_id", as: "rotasi_personel_master" });
RotasiPersonelMaster.hasMany(RotasiPersonelUraian, { foreignKey: "rotasi_personel_master_id", as: "rotasi_personel_uraian_list" });
PatrolUdaraUraian.belongsTo(PatroliUdaraMaster, { foreignKey: "patroli_udara_master_id", as: "patroli_udara_master_detail" });
PatroliUdaraMaster.hasMany(PatrolUdaraUraian, { foreignKey: "patroli_udara_master_id", as: "patrol_udara_uraian_list" });
PatrolDaratUraian.belongsTo(PatroliDaratMaster, { foreignKey: "patroli_master_id", as: "patroli_darat_master" });
PatroliDaratMaster.hasMany(PatrolDaratUraian, { foreignKey: "patroli_master_id", as: "patrol_darat_uraian_list" });
LogbookRaUraian.belongsTo(LogbookRaMaster, { foreignKey: "logbook_ra_master_id", as: "logbook_ra_master" });
LogbookRaMaster.hasMany(LogbookRaUraian, { foreignKey: "logbook_ra_master_id", as: "logbook_ra_uraian_list" });
LaporanTerminalKargoUraian.belongsTo(LaporanTerminalKargoMaster, { foreignKey: "laporan_terminal_kargo_master_id", as: "laporan_terminal_kargo_master_detail" });
LaporanTerminalKargoMaster.hasMany(LaporanTerminalKargoUraian, { foreignKey: "laporan_terminal_kargo_master_id", as: "laporan_terminal_kargo_uraian_list" });
LaporanPatroliRandomUraian.belongsTo(LaporanPatroliRandomMaster, { foreignKey: "laporan_patroli_random_master_id", as: "laporan_patroli_random_master_detail" });
LaporanPatroliRandomMaster.hasMany(LaporanPatroliRandomUraian, { foreignKey: "laporan_patroli_random_master_id", as: "laporan_patroli_random_uraian_list" });
//FormKemajuanPersonelUraian.belongsTo(FormKemajuanPersonelMaster, { foreignKey: "form_kemajuan_personel_master_id", as: "form_kemajuan_personel_master_detail" });
//FormKemajuanPersonelMaster.hasMany(FormKemajuanPersonelUraian, { foreignKey: "form_kemajuan_personel_master_id", as: "form_kemajuan_personel_uraian_list" });
ChecklistPenyisiran.belongsTo(PenyisiranRuangTungguMaster, { foreignKey: "penyisiran_ruang_tunggu_master_id", as: "penyisiran_ruang_tunggu_master_detail" });
PenyisiranRuangTungguMaster.hasMany(ChecklistPenyisiran, { foreignKey: "penyisiran_ruang_tunggu_master_id", as: "checklist_penyisiran_list" });
ChecklistHarianPatroliUraian.belongsTo(ChecklistHarianPatroliMaster, { foreignKey: "checklist_harian_patroli_master_id", as: "checklist_harian_patroli_master_detail" });
ChecklistHarianPatroliMaster.hasMany(ChecklistHarianPatroliUraian, { foreignKey: "checklist_harian_patroli_master_id", as: "checklist_harian_patroli_uraian_list" });
UraianPI.belongsTo(FormPengendalianPI, { foreignKey: "form_pengendalian_pi", as: "form_pi" });
FormPengendalianPI.hasMany(UraianPI, { foreignKey: "form_pengendalian_pi", as: "uraian_pi_list" });
UraianGate.belongsTo(FormPengendalianPI, { foreignKey: "form_pengendalian_pi", as: "form_pi" });
FormPengendalianPI.hasMany(UraianGate, { foreignKey: "form_pengendalian_pi", as: "uraian_gate_list" });